#!/bin/sh
set -e
dir="`git rev-parse --show-toplevel`"
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files | \
  ctags --tag-relative \
  -L - \
  -f "$dir/$$.tags" \
  --exclude=.git \
  --exclude=vendor \
  --exclude=node_modules \
  --exclude=coverage \
  --exclude=public
mv "$dir/$$.tags" "$dir/.tags"
